#%RAML 1.0
---
title: "Fix Simulator API"
version: v1
protocols: HTTPS
mediaType: application/json
baseUri: https://fs.16financial.net/api/fixsimulator/{version}

types:
  ResponseError: !include ../schemas/dist/mss/type_fix_simulator_caller_error.json

  Id:
    type: integer
    description: the global unique id of an order
  MsgType?:
    type: string
    description: fix msg type
    enum:
      - MSG_TYPE_NEW_ORDER_SINGLE
      - MSG_TYPE_CANCEL_REQUEST
      - MSG_TYPE_REPLACE_REQUEST
      - MSG_TYPE_MATCH_ALL
    example: MSG_TYPE_REPLACE_REQUEST
  SessionId?:
    type: string
    description: sessionId configured in fix simulator, must match (FIX.4.2:[A-Za-z0-9]+?->[A-Za-z0-9]+?)|(\*)
    example: FIX.4.2:INCAAPEX->TRYCOSECS
  Page?:
    type: integer
    description: Specify the page that you want to retrieve
    default: 1
  Limit?:
    type: integer
    description: Specify the amount of items that will be retrieved per page
    default: 10

  FsOrderListItem: !include ../schemas/dist/mss/type_fix_simulator_order_list_item.json
  FsOrderDetailItem: !include ../schemas/dist/mss/type_fix_simulator_order_detail_item.json
  ScriptListItem: !include ../schemas/dist/mss/type_fix_simulator_script_list.json
  ScriptDetailItem: !include ../schemas/dist/mss/type_fix_simulator_script_detail.json

  PageItem: !include ../schemas/dist/mss/type_paged.json

  FsOrderListReq: !include ../schemas/dist/mss/type_fix_simulator_order_list_req.json
  ScriptListReq: !include ../schemas/dist/mss/type_fix_simulator_script_list_req.json
  ScriptCreateOrUpdateReq: !include ../schemas/dist/mss/type_fix_simulator_script_create_or_update_req.json
  ScriptDeleteReq: !include ../schemas/dist/mss/type_fix_simulator_script_delete_req.json
  ScriptDetailGetReq: !include ../schemas/dist/mss/type_fix_simulator_script_detail_get_req.json
  ScriptDetailsQueryReq: !include ../schemas/dist/mss/type_fix_simulator_script_details_query_req.json

traits:
  caller_error:
    usage: Apply to method for generating caller side error
    responses:
      400:
        body:
          type: ResponseError
        description: caller side error, primary for incorret parameters

  not_found_error:
    usage: Apply to detail method for getting no result
    responses:
      404:
        body:
          type: ResponseError
        description: can't get detail info

  caller_ok:
    usage: Apply to method for generateing ok
    responses:
      200:
        description: empty return body


  paged:
    usage: Apply to .list method for pagination response
    responses:
      200:
        body:
          type: object
          properties:
            pagination: PageItem

  order_list_response:
    usage: Return order.list result
    responses:
      200:
        body:
          type: object
          properties:
            data:
              type: array
              items: FsOrderListItem

  order_detail_response:
    usage: Return order.detail result
    responses:
      200:
        body:
          type: FsOrderDetailItem

  script_list_response:
    usage: Return script.list result
    responses:
      200:
        body:
          type: object
          properties:
            data:
              type: array
              items: ScriptListItem

  script_detail_response:
    usage: Return a script detail
    responses:
      200:
        body:
          type: ScriptDetailItem

  script_details_response:
    usage: Return details of different versions of scirpt
    responses:
      200:
        body:
          type: array
          properties:
            data:
              type: arrary
              items: ScriptDetailItem

/order.list:
  (serviceName): fix-simulator
  post:
    displayName: List Orders
    description: '
    Query orders from fix-simulator, use in list page and search result page'
    body: FsOrderListReq
    is: [paged, caller_error, order_list_response]


/order.detail:
  (serviceName): fix-simulator
  get:
    displayName: Get Order Detail
    description: '
    Query order detail info, use in detail page'
    queryParameters:
        id: Id
    is: [caller_error, order_detail_response, not_found_error]


/script.list:
  (serviceName): fix-simulator
  get:
    displayName: List Scripts
    description: '
    List scripts from fix-simulator, used in script list page.'
    queryParameters:
      msg_type: MsgType
      session_id: SessionId
      page: Page
      limit: Limit
    is: [paged, script_list_response, caller_error]

/script.createOrUpdate:
  (serviceName): fix-simulator
  post:
    displayName: Create Or Update Script
    description: '
    Create or update a script.'
    body: ScriptCreateOrUpdateReq
    is: [caller_error]
    responses:
      200:
        body:
          type: object
          properties:
            data:
              type: integer
              description: the current version of this group of scripts.

/script.delete:
  (serviceName): fix-simulator
  post:
    displayName: Delete Script
    description: '
    Delete script from fix-simulator(change the newest version of script into disable status).'
    body: ScriptDeleteReq
    is: [caller_error, caller_ok]

/script.get:
  (serviceName): fix-simulator
  get:
    displayName: Get Script Detail
    description: '
    Get script detail info. If versions is nil, return newest version. If fix simulator cannot find a script, it returns a 404 error.'
    queryParameters:
      session_id: SessionId
      msg_type: MsgType
      version?:
        type: integer
        description: if version is nil or less than 1, fix simulator will return the newest version.
    is: [caller_error, script_detail_response, not_found_error]
